services:
  server:
    build: .
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - app_network
    
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - app_network
    
volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge